
data_info_dict = {
    'MAYO': {'data_path': '.../benchmark/datasets/MAYO/group_data',
        'group_num': 6,
        'split': [3, 1, 2],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 1000,
        'channel': 1,
        'seq_len': 3,
        'downstream': 'disorder',
    },
    'FNUSA': {'data_path': '.../benchmark/datasets/FNUSA/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 1000,
        'channel': 1,
        'seq_len': 3,
        'downstream': 'disorder',
    },
    'CHBMIT': {'data_path': '.../benchmark/datasets/CHBMIT/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 256,
        'channel': 23,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'SleepEDFx': {
        'data_path': '.../benchmark/datasets/SleepEDFx/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 5,
        'sfreq': 100,
        'channel': 1,
        'seq_len': 30,
        'downstream': 'disorder',
    },
    'ADFD':{
        'data_path': '.../benchmark/datasets/ADFD/group_data_AD',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 250,
        'channel': 19,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'ADHD_Adult':{
        'data_path': '.../benchmark/datasets/Adults_ADHD/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 256,
        'channel': 2,
        'seq_len': 5,
        'downstream': 'disorder',
    },
    'ADHD_Child':{
        'data_path': '.../benchmark/datasets/Child_ADHD/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 128,
        'channel': 19,
        'seq_len': 5,
        'downstream': 'disorder',
    },
    'Depression_122_BDI':{
        'data_path': '.../benchmark/datasets/Depression_122/group_data_BDI',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 250,
        'channel': 64,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'Depression_122_STAI':{
        'data_path': '.../benchmark/datasets/Depression_122/group_data_STAI',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 3,
        'sfreq': 250,
        'channel': 64,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'Schizophrenia_28':{
        'data_path': '.../benchmark/datasets/EEG_schizophrenia/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 250,
        'channel': 19,
        'seq_len': 5,
        'downstream': 'disorder',
    },
    'MPHCE_mdd':{
        'data_path': '.../benchmark/datasets/MPHCE/group_data_mdd',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 256,
        'channel': 19,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'MPHCE_state':{
        'data_path': '.../benchmark/datasets/MPHCE/group_data_state',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 3,
        'sfreq': 256,
        'channel': 19,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'SEED_IV':{
        'data_path': '.../benchmark/datasets/SEED_IV/group_data',
        'group_num': 6,
        'split': [3, 1, 2],
        'various_ch_num': False,
        'n_class': 4,
        'sfreq': 200,
        'channel': 62,
        'seq_len': 4,
        'downstream': 'Motor imagine',
    },
    'SD_71':{
        'data_path': '.../benchmark/datasets/Sleep_Deprivation/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 250,
        'channel': 61,
        'seq_len': 5,
        'downstream': 'disorder',
    },
    'EEGMat':{
        'data_path': '.../benchmark/datasets/EEGMat/group_data',
        'group_num': 4,
        'split': [2, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 250,
        'channel': 19,
        'seq_len': 10,
        'downstream': 'Motor imagine',
    },
    'DEAP':{
        'data_path': '.../benchmark/datasets/DEAP/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 4,
        'sfreq': 128,
        'channel': 32,
        'seq_len': 10,
        'downstream': 'emotion',
    },
    'EEGMMIDB_R':{
        'data_path': '.../benchmark/datasets/EEGMMIDB/group_data_R',
        'group_num': 6,
        'split': [3, 1, 2],
        'various_ch_num': False,
        'n_class': 4,
        'sfreq': 160,
        'channel': 64,
        'seq_len': 4,
        'downstream': 'Motor imagine',
    },
    'EEGMMIDB_I':{
        'data_path': '.../benchmark/datasets/EEGMMIDB/group_data_I',
        'group_num': 6,
        'split': [3, 1, 2],
        'various_ch_num': False,
        'n_class': 4,
        'sfreq': 160,
        'channel': 64,
        'seq_len': 4,
        'downstream': 'Motor imagine',
    },
    'UCSD_ON': {'data_path': '.../benchmark/datasets/UCSD/group_data_on',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 256,
        'channel': 32,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'UCSD_OFF': {'data_path': '.../benchmark/datasets/UCSD/group_data_off',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 256,
        'channel': 32,
        'seq_len': 10,
        'downstream': 'disorder',
    },
    'ISRUC': {'data_path': '.../benchmark/datasets/ISRUC/group_data',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 5,
        'sfreq': 200,
        'channel': 6,
        'seq_len': 30,
        'downstream': 'disorder',
    },
    'AD-65': {'data_path': '.../benchmark/datasets/ADFD/group_data_AD',
        'group_num': 5,
        'split': [3, 1, 1],
        'various_ch_num': False,
        'n_class': 2,
        'sfreq': 250,
        'channel': 19,
        'seq_len': 10,
        'downstream': 'disorder',
    },
}
